const productData = [
  {
    id: 1,
    image: require("~/assets/images/news/news-1.png"),
    name: "Mavin tham gia Hội nghị thượng đỉnh liên kết Doanh nghiệp Limitless 2022 của World Vision",
    rating: "4.9",
    category: "Tin Mavinex",
    date: "02/07/2020",
    createdBy: "Admin",
    quality: 112,
    status: "Active",
  },
  {
    id: 2,
    image: require("~/assets/images/news/news-2.png"),
    name: "Mavin được trao giải “Doanh nghiệp tiên phong Đông Nam Á” từ SAP",
    rating: "3.1",
    category: "Tin MavinFood",
    date: "02/06/2020",
    createdBy: "Minh - Mavinex",
    quality: 60,
    status: "Active",
  },
  {
    id: 3,
    image: require("~/assets/images/news/news-3.png"),
    name: "Mavin và Fish&Co (Cameroon) hợp tác nuôi trồng thủy sản bền vững",
    rating: "4.3",
    category: "Tin Cailay",
    date: "02/03/2020",
    createdBy: "Thu - MavinFood",
    quality: 58,
    status: "Pending",
  },
  {
    id: 4,
    image: require("~/assets/images/news/news-4.png"),
    name: "Mavin Feed 2022: Thích ứng nhanh với tình hình mới",
    rating: "4.9",
    category: "Tin Cailay",
    date: "02/04/2020",
    createdBy: "Trang - Cailay",
    quality: 98,
    status: "Active",
  },
  {
    id: 5,
    image: require("~/assets/images/news/news-5.png"),
    name: "Chính thức vận hành Hệ thống Đào tạo trực tuyến E-learning",
    rating: "2.5",
    category: "Tin Mavinex",
    date: "02/05/2020",
    createdBy: "Minh - Mavinex",
    quality: 38,
    status: "Deactive",
  },
];
export { productData };
